# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 243c4bb6b71be72f78188fe9be70a9cd0456d955e612627f4fe762b9fad8aa9ca7e6f2e6b1edfa26c442facf56019d836392682ac2473f870644e2e476731613

test:
  secret_key_base: fdb6d8f55253a77f0e0d16d1ed943717106029d9a01853f038c71b9e740acf280a88027392d98c94ddca0522d36289373ee8ba1d4da3574af2166c64904f973b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
